### ISSUE TITLE
remove prometheus api sugar 

### ISSUE THREAD

**Issue by dozer-jang** [kuoss/venti#15]
기존에 지원하던 api들 중 prometheus 쿼리로 가능한 것들은 query로 전환하려하는데 web에서 호출하는 부분 수정 가능할까요?

/prometheus/time -> /prometheus/query?expr=time()
/prometheus/namespaces -> /prometheus/query?expr=kube_namespace_created
/prometheus/pods/:namespace -> /prometheus/query?expr=kube_pod_created{namespace="namespace01"}
/prometheus/nodes -> /prometheus/query?expr=kube_node_created

/query 인터페이스에 param으로 호출 가능한 결과들이 편의성을 위해서 하드코딩된 인터페이스르 제공하고있다고 생각합니다.

**Comment by jmnote** [comment]
#34 로 해결되었습니다. close합니다.
