### ISSUE TITLE
query & select datasource

### ISSUE THREAD

**Issue by jmnote** [kuoss/venti#26]
AS-IS
| path | description |
| ---- | ----------- |
| /api/prometheus/query | main prometheus에 대한 query |
| /api/prometheus/query?host=aaaa | aaaa prometheus에 대한 query |
| /api/lethe/query | main lethe에 대한 query |
| /api/lethe/query?host=bbbb | bbbb lethe에 대한 query |

TO-BE
| path | description |
| ---- | ----------- |
| /api/query | main prometheus에 대한 query
| /api/query?dstype=prometheus | main prometheus에 대한 query
| /api/query?dstype=lethe | main lethe에 대한 query
| /api/query?dsid=1 | datasource 1번에 대한 query

**Comment by jmnote** [comment]
이건 일단 보류...

host 파라미터가 있는 경우 해당 host로, 없는 경우 main으로 query하는 기능이 원래 있었습니다. 현재 시점에 IsDefault라고 된 게 그와 관련된 건데, IsMain으로 바꿀 겁니다.

어느 datasource에 query할지는 정해줘야 하므로, datasource 순서에 따라 배정되는 dsid를 사용하고자 합니다.

**Comment by dozer-jang** [comment]
음 일단 제가 이해한 걸 정리해보면 아래로 이해했어요.

1. 기존에 `DatasourceConfig` 파일을 읽은 후, `Datasources` discovery를 통해 초기화 합니다. 
2. discovery 과정에서 `Datasource` 의 필드 중 `Host`를 지정하는 경우 default `Datasource`입니다. 
3. venti에 query 요청이 들어왔을 때 `DatasourceType`을 알 수 없는 경우 default `Datasource` 에 query를 수행한다. 



그리고 앞으로 변경할 사항들은 아래로 이해했는데 맞을까요?

1. `Datasource` 타입마다 쿼리를 구분하는 방식이 api의 path대신 `dstype`이라는 qurey string으로 바꿀 예정
2. `Datasource`마다 `dsid`를 정해서 만약 쿼리에 어떤 `dstype`이 명시되어있지 않으면 `dsid` 순으로 쿼리한다.

**Comment by jmnote** [comment]
위에 썼듯이 query는 main prometheus, non-main prometheus, main lethe, non-main lethe에 대해 수행하는 경우의 수가 있을 것 같습니다.

datasourceStore 로직에 대한 설명이 부족한 것 같아서 다음 이슈에 작성하였습니다.

#27

**Comment by dozer-jang** [comment]
그런데 main과 sub를 나누는 이유가 혹시 멀티클러스터를 대응하기 위함인가요?

**Comment by jmnote** [comment]
네 맞습니다. 대시보드를 만들다 보니까 1) main에 대한 조회과, 2) main를 제외한 나머지 모든 sub들에 대한 조회로 나눌 필요가 있더라구요.

**Comment by jmnote** [comment]
#34 의 remoteStore로 해결되었으므로 close합니다.
